server.port=8081
spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5433/thesisdb
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

ai.service.base-url=${AI_SERVICE_URL:https://nl2sql-ai-0n39.onrender.com}
